name: 🏁 Windows Builds
on:
  workflow_call:
    inputs:
      target:
        required: true
        type: string

# Global Settings
# SCONS_CACHE for windows must be set in the build environment
env:
  # Used for the cache key. Add version suffix to force clean build.
  GODOT_BASE_BRANCH: master
  SCONS_CACHE_MSVC_CONFIG: true

concurrency:
  cancel-in-progress: true
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-windows-${{ inputs.target }}

jobs:
  build-windows:
    # Windows 10 with latest image
    runs-on: "ubuntu-20.04"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Windows build - ${{ inputs.target }}
            cache-name: windows
            target: ${{ inputs.target }}
            # Skip debug symbols, they're way too big with MSVC.
            sconsflags: debug_symbols=no use_mingw=yes
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install mingw64
        shell: sh
        run: |
          sudo apt-get install mingw-w64
          sudo update-alternatives --set x86_64-w64-mingw32-gcc /usr/bin/x86_64-w64-mingw32-gcc-posix
          sudo update-alternatives --set x86_64-w64-mingw32-g++ /usr/bin/x86_64-w64-mingw32-g++-posix

      - name: Setup python and scons
        uses: ./.github/actions/deps

      - name: Compilation
        uses: ./.github/actions/build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }}
          platform: windows
          target: ${{ matrix.target }}
          tests: ${{ matrix.tests }}
      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: windows
          path: ./gdextension_build/build/*
